version: '3'
services:
  jackwui:
    build: .
    restart: always
    container_name: jackwui
    expose:
      - "3015"
    environment:
      - VIRTUAL_HOST=jackwui.ptah.tech
      - VIRTUAL_PORT=3015
      - LETSENCRYPT_HOST=jackwui.ptah.tech
      - LETSENCRYPT_EMAIL=febef.dev@gmail.com
networks:
  default:
     external:
       name: webproxy
